from django.urls import path
from . import views


urlpatterns = [
    path("create_orders/", views.order_create, name="order_create"),
    path(
        "admin/order/<int:order_id>/pdf/",
        views.admin_order_pdf,
        name="admin_order_pdf",
    ),
    path("State_Abuja/", views.state_abuja, name="state_abuja"),
    path("State_Abia/", views.state_abia, name="state_abia"),
    path("State_Adamawa/", views.state_adamawa, name="state_adamawa"),
    path("State_Akwa_Ibom/", views.state_akwa_ibom, name="state_akwa_ibom"),
    path("State_Anambra/", views.state_anambra, name="state_anambra"),
    path("State_Bauchi/", views.state_bauchi, name="state_bauchi"),
    path("State_Bayelsa/", views.state_bayelsa, name="state_bayelsa"),
    path("State_Benue/", views.state_benue, name="state_benue"),
    path("State_Borno/", views.state_borno, name="state_borno"),
    path("State_Cross_River/", views.state_cross_river, name="state_cross_river"),
    path("State_Delta/", views.state_delta, name="state_delta"),
    path("State_Ebonyi/", views.state_ebonyi, name="state_ebonyi"),
    path("State_Edo/", views.state_edo, name="state_edo"),
    path("State_Ekiti/", views.state_ekiti, name="state_ekiti"),
    path("State_Enugu/", views.state_enugu, name="state_enugu"),
    path("State_Gombe/", views.state_gombe, name="state_gombe"),
    path("State_Imo/", views.state_imo, name="state_imo"),
    path("State_Jigawa/", views.state_jigawa, name="state_jigawa"),
    path("State_Kaduna/", views.state_kaduna, name="state_kaduna"),
    path("State_Kano/", views.state_kano, name="state_kano"),
    path("State_Katsina/", views.state_katsina, name="state_katsina"),
    path("State_Kebbi/", views.state_kebbi, name="state_kebbi"),
    path("State_Kogi/", views.state_kogi, name="state_kogi"),
    path("State_Kwara/", views.state_kwara, name="state_kwara"),
    path("State_Lagos/", views.state_lagos, name="state_lagos"),
    path("State_Nassarawa/", views.state_nassarawa, name="state_nassarawa"),
    path("State_Niger/", views.state_niger, name="state_niger"),
    path("State_Ogun/", views.state_ogun, name="state_ogun"),
    path("State_Ondo/", views.state_ondo, name="state_ondo"),
    path("State_Osun/", views.state_osun, name="state_osun"),
    path("State_Oyo/", views.state_oyo, name="state_oyo"),
    path("State_Plateau/", views.state_plateau, name="state_plateau"),
    path("State_Rivers/", views.state_rivers, name="state_rivers"),
    path("State_Sokoto/", views.state_sokoto, name="state_sokoto"),
    path("State_Taraba/", views.state_taraba, name="state_taraba"),
    path("State_Yobe/", views.state_yobe, name="state_yobe"),
    path("State_Zamfara/", views.state_zamfara, name="state_zamfara"),
]
