# Generated by Django 5.0 on 2023-12-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='M', max_length=10),
        ),
    ]
