# Generated by Django 5.0 on 2024-03-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='ankle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='knee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='laps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='neck',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sleeve_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='top_length',
            field=models.IntegerField(null=True),
        ),
    ]
