# Generated by Django 5.0 on 2024-01-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_alter_measurement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='user',
        ),
    ]
