# Generated by Django 5.0 on 2024-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_alter_measurement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='chest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='shoulder',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sleeve_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='thigh',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='trouser_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist',
            field=models.IntegerField(null=True),
        ),
    ]
