# Generated by Django 5.0 on 2024-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_measurement_ankle_measurement_knee_measurement_laps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='vest', max_length=50),
        ),
    ]
