# Generated by Django 5.0 on 2024-02-04 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0003_alter_measurement_chest_alter_measurement_shoulder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nysc.measurement'),
        ),
    ]
