# Generated by Django 5.0 on 2024-04-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0003_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
