# Generated by Django 5.0 on 2024-04-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0004_countdowntimer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountdownTimer',
        ),
    ]
