# Generated by Django 5.0 on 2024-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0005_delete_countdowntimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('kakhi', 'Kakhi'), ('vest', 'Vest'), ('cap', 'Cap')], default='vest', max_length=50),
        ),
    ]
