# Generated by Django 5.0 on 2024-02-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0005_remove_product_measurement_measurement_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='product',
        ),
    ]
