# Generated by Django 5.0 on 2024-04-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='vest', max_length=50),
        ),
    ]
