# Generated by Django 5.0 on 2024-02-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0006_remove_measurement_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
