# Generated by Django 5.0 on 2024-02-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0008_event_delete_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
