# Generated by Django 5.0 on 2024-05-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0008_alter_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
