# Generated by Django 5.0 on 2024-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0009_countdowndatetime_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CountdownDateTime',
        ),
    ]
