# Generated by Django 5.0 on 2024-02-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0010_countdownevent_delete_countdowndatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CountdownEvent',
        ),
    ]
