# Generated by Django 5.0 on 2024-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state_of_deployment',
            field=models.CharField(default="My Father's Land", max_length=50),
        ),
    ]
