# Generated by Django 5.0 on 2024-01-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_state_of_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nysc_call_up_number',
            field=models.CharField(default='Your Call Up Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state_of_deployment',
            field=models.CharField(default="Your Father's Land", max_length=50),
        ),
    ]
