# Generated by Django 5.0 on 2024-01-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_nysc_call_up_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nysc_call_up_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state_of_deployment',
        ),
    ]
