# Generated by Django 5.0 on 2024-01-02 19:45

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_inspo_photo_video_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='jume_videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
