# Generated by Django 5.0 on 2023-12-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paystack_ref',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
