# Generated by Django 5.0 on 2024-02-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
        ('orders', '0002_alter_orderitem_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesaurement', to='nysc.measurement'),
        ),
    ]
